-- LSP Saga Configuration
-- LSP UI enhancements

require("lspsaga").setup({
  ui = {
    border = "rounded",
    winblend = 0,
    expand = "",
    collapse = "",
    code_action = "󰌵",
    incoming = "󰏷",
    outgoing = "󰏻",
    hover = "󰗘",
    kind = {},
  },
  hover = {
    max_width = 0.9,
    max_height = 0.8,
    open_link = "gx",
    open_browser = "!open ",
  },
  diagnostic = {
    on_insert = false,
    on_insert_follow = false,
    insert_winblend = 0,
    show_code_action = true,
    show_source = true,
    jump_num_shortcut = true,
    max_width = 0.7,
    max_height = 0.6,
    text_hl_follow = false,
    border_follow = true,
    extend_relatedInformation = false,
    keys = {
      exec_action = "o",
      quit = { "q", "<ESC>" },
      go_action = "g",
    },
  },
  code_action = {
    num_shortcut = true,
    show_server_name = false,
    extend_gitsigns = true,
    keys = {
      quit = "q",
      exec = "<CR>",
    },
  },
  lightbulb = {
    enable = true,
    enable_in_insert = true,
    sign = true,
    sign_priority = 40,
    virtual_text = true,
  },
  symbol_in_winbar = {
    enable = true,
    separator = " 󰁔 ",
    ignore_patterns = {},
    hide_keyword = true,
    show_file = true,
    folder_level = 2,
    respect_root = false,
    color_mode = true,
  },
  outline = {
    win_position = "right",
    win_width = 30,
    auto_preview = true,
    auto_refresh = true,
    auto_close = true,
    custom_sort = nil,
    keys = {
      jump = "o",
      expand_collapse = "u",
      quit = "q",
    },
  },
  callhierarchy = {
    show_detail = false,
    keys = {
      edit = "e",
      vsplit = "s",
      split = "i",
      tabe = "t",
      jump = "o",
      quit = "q",
      expand_collapse = "u",
    },
  },
  rename = {
    quit = "<C-c>",
    exec = "<CR>",
    mark = "x",
    confirm = "<CR>",
    in_select = true,
  },
  finder = {
    max_height = 0.5,
    left_width = 0.3,
    default = "ref+def",
    layout = "normal",
    silent = false,
    filter = {},
    fname_width = 0.5,
    fname_width_min = 0.3,
    sp_ins = "󰁔",
    sp_rep = "󰁔",
    sp_above = "󰁔",
    sp_below = "󰁔",
    sp_left = "󰁔",
    sp_right = "󰁔",
    keys = {
      shuttle = "[w",
      toggle_or_jump = "<CR>",
      vsplit = "s",
      split = "i",
      tabe = "t",
      tabnew = "r",
      quit = { "q", "<ESC>" },
      close = "<C-c>k",
    },
  },
  definition = {
    edit = "<C-c>o",
    vsplit = "<C-c>v",
    split = "<C-c>i",
    tabe = "<C-c>t",
    quit = "q",
  },
  scroll_preview = {
    scroll_down = "<C-f>",
    scroll_up = "<C-b>",
  },
  request_timeout = 2000,
  preview = {
    lines_above = 0,
    lines_below = 10,
  },
  implement = {
    enable = true,
    sign = true,
    lang = {},
    virtual_text = true,
    priority = 40,
  },
  scroll_preview = {
    scroll_down = "<C-f>",
    scroll_up = "<C-b>",
  },
})
